name: create-environment
# Create environment in your tenant

on:
  pull_request:
    branches: [ main ]

jobs:
  create:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: create-environment action
      uses: microsoft/powerplatform-actions/create-environment@3a66fd4
      with:
        user-name: 'sbhalgat@ppdevtools.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        name: 'swaptest'